url: "https://freudenberggroup.github.io"
baseurl: "/data-privacy-webpages"

title: "Freudenberg Group"
plugins:
  - jekyll-postcss

postcss:
  cache: false

language_default: en

collections_dir: content
collections:
  ar:
    output: true
    permalink: /:collection/:slug
  es:
    output: true
    permalink: /:collection/:slug
  da:
    output: true
    permalink: /:collection/:slug
  de:
    output: true
    permalink: /:collection/:slug
  en:
    output: true
    permalink: /:collection/:slug
  zh:
    output: true
    permalink: /:collection/:slug
