url: "https://freudenberggroup.github.io"
baseurl: "/data-privacy-webpages"

title: "" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-postcss

postcss:
  cache: false

language_default: en

collections_dir: content
collections:
  de:
    output: true
    permalink: /:collection/:slug
  en:
    output: true
    permalink: /:collection/:slug
  zh:
    output: true
    permalink: /:collection/:slug
